### ISSUE TITLE
Ethernet module is not powered from USB

### ISSUE THREAD

**Issue by CameronDevine** [Industruino/documentation#1]
I was having trouble getting my Ethernet module to work. The problem turned out to be that I was only powering the D21G from the USB port. It would be worth mentioning in the documentation that you must power the D21G from the 8-24V input for the Ethernet module to work.

**Comment by tomtobback** [comment]
Hi, thank you for the feedback, i have added a note on https://github.com/Industruino/documentation/blob/master/ethernet.md
