### ISSUE TITLE
Modbus documentation outdated

### ISSUE THREAD

**Issue by albertmonteith** [Industruino/documentation#3]
The Google Drive link to the SimpleModbusMaster/SimpleModbusClient library is broken.
This library is now available [here](https://github.com/BlackBrix/Simple-Modbus-Master), but is not maintained anymore.
A more developed and maintained variant of this library is available [here](https://github.com/angeloc/simplemodbusng).
I have not tested these libraries because they abstract the Modbus protocol into a format that is only useful for very simple PLC applications.

Instead, the native [ArduinoModbus library](https://www.arduino.cc/reference/en/libraries/arduinomodbus/) provides a lot more control of the Modbus functions. ArduinoModbus is dependent on the [ArduinoRS485 library](https://www.arduino.cc/reference/en/libraries/arduinors485/) which must be modified slightly to work with the Ind.I/O + D21G. 
[Here](https://github.com/Industruino/documentation/files/8499282/ArduinoRS485.Industruino.D21G.zip) are two files to be replaced in the ArduinoRS485 library. The only changes I made were to use the TXENABLEPIN (pin 9 on D21G) instead of two separate de (tx enable) and re (rx enable) pins, since they are connected on the Ind.I/O.

**Comment by tomtobback** [comment]
many thanks for the feedback, i have updated the [doc](https://github.com/Industruino/documentation/blob/master/indio.md#modbus), pointing to a clone of the original google drive version. i have also added a link to this issue for using the official ArduinoModbus library for RTU, and a link to a previous example of that library for TCP.

**Comment by tomtobback** [comment]
it is now possible to use this constructor for the RS485, without having to modify the library:
```RS485Class Rs485(Serial, 1, 9, 9);  // Industruino INDIO RS485 port```
