### ISSUE TITLE
Beware of interrupts 

### ISSUE THREAD

**Issue by albertmonteith** [Industruino/documentation#4]
I managed to brick a D21G board.
My sketch included Ethernet communications, SerialUSB printing  and an interrupt routing triggered by a pin to update a counter (no printing in the ISR).
On their own, each of these functions work without a problem, but when put together the program would hang at seemingly random durations after starting.
This continued with repeated efforts of modifying the code, uploading and running, until the D21G it stopped responding permanently.

It seems like interrupts are notorious for causing trouble in Arduinos, possibly because mundane functions like print() make use of interrupts. Combined with your own interrupt routing and you have a recipe for trouble.

It might be good to mention that interrupts can cause undetermined behaviour and possibly break your device in the documentation since this is an expensive fix.

**Comment by tomtobback** [comment]
thanks for the feedback. have you tried to put the board into bootloader mode again by tapping the reset button twice? the button is on the bottom of the topboard, you will have to take the plastic casing off to reach it under the LCD screen. that usually solves such situations.
